env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  import/no-extraneous-dependencies: off
  import/extensions: off
  import/prefer-default-export: off
  import/no-unresolved: off
  no-unused-expressions: off
